### ISSUE TITLE
Configuration: Provide Advanced Settings

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-drupal-8#7]
Related to #3.

* Provide the availability to set a custom api endpoint;
* Provide a setting to disable Coyote filtering of nodes when rendered;
* Provide a setting to ignore incoming Coyote webhook calls;
* Provide a setting to configure whether unpublished nodes should be processed when batch importing.

**Comment by catorghans** [comment]
For item 3: Is this allowed als result from \RestApiController::callback to the coyote backend ?

return new JsonResponse(['status' => 'ignored']);

**Comment by jkva** [comment]
> For item 3: Is this allowed als result from \RestApiController::callback to the coyote backend ?
> 
> return new JsonResponse(['status' => 'ignored']);

Very good question - yes, that seems a valid response, the Coyote Server does record the responses coming from webhook calls. There should also be a corresponding 'updated' response in the success scenario.

It would seem that the 'ignored' response should also be status 404, while the 'success' response should be 200.

**Comment by catorghans** [comment]
OK, 404 (not found) is possible, but would 403 (forbidden) not be better in this case?

**Comment by jkva** [comment]
403 seems apt in the case of calls being ignored, agreed. 404 would be in case calls are accepted but the resource does not exist drupal-side.

**Comment by catorghans** [comment]
ok, 403 it is.

**Comment by catorghans** [comment]
I am going to add a "unpublished" check in NodeViewAlterPostRenderHook now. And create a separate button "batch importing" on the config form which also takes the unpublished config-option into account when creating #1
